# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22c216a79314957cbb8fa142004e165f7758c147eb7030e411613a2b68bd695930671e227388457aa44a4f07f0b0c7e380de128292d13210ca8a42623ed1dad5

test:
  secret_key_base: 1a975b39257fc10a01b236618f69ce4a209b220208227890d3aadc9e39f5f6c87a653c9a72aed3737dbe15a2040f24f8e78f8b3b9fd259c8bf6e234f1906671d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
